/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CokSatanlarRouteImport } from './routes/cok-satanlar'
import { Route as FavorilerRouteImport } from './routes/favoriler'
import { Route as HesabimRouteImport } from './routes/hesabim'
import { Route as SepetRouteImport } from './routes/sepet'
import { Route as StilDanismaniRouteImport } from './routes/stil-danismani'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAyarlarRouteImport } from './routes/admin.ayarlar'
import { Route as AdminKategorilerRouteImport } from './routes/admin.kategoriler'
import { Route as AdminSiparislerRouteImport } from './routes/admin.siparisler'
import { Route as AdminUrunlerRouteImport } from './routes/admin.urunler'
import { Route as ApiStilDanismaniRouteImport } from './routes/api/stil-danismani'
import { Route as BilgiSlugRouteImport } from './routes/bilgi.$slug'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'
import { Route as UrunSlugRouteImport } from './routes/urun.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CokSatanlarRoute = CokSatanlarRouteImport.update({
  id: '/cok-satanlar',
  path: '/cok-satanlar',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorilerRoute = FavorilerRouteImport.update({
  id: '/favoriler',
  path: '/favoriler',
  getParentRoute: () => rootRouteImport,
} as any)
const HesabimRoute = HesabimRouteImport.update({
  id: '/hesabim',
  path: '/hesabim',
  getParentRoute: () => rootRouteImport,
} as any)
const SepetRoute = SepetRouteImport.update({
  id: '/sepet',
  path: '/sepet',
  getParentRoute: () => rootRouteImport,
} as any)
const StilDanismaniRoute = StilDanismaniRouteImport.update({
  id: '/stil-danismani',
  path: '/stil-danismani',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAyarlarRoute = AdminAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKategorilerRoute = AdminKategorilerRouteImport.update({
  id: '/kategoriler',
  path: '/kategoriler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiparislerRoute = AdminSiparislerRouteImport.update({
  id: '/siparisler',
  path: '/siparisler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUrunlerRoute = AdminUrunlerRouteImport.update({
  id: '/urunler',
  path: '/urunler',
  getParentRoute: () => AdminRoute,
} as any)
const ApiStilDanismaniRoute = ApiStilDanismaniRouteImport.update({
  id: '/api/stil-danismani',
  path: '/api/stil-danismani',
  getParentRoute: () => rootRouteImport,
} as any)
const BilgiSlugRoute = BilgiSlugRouteImport.update({
  id: '/bilgi/$slug',
  path: '/bilgi/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const UrunSlugRoute = UrunSlugRouteImport.update({
  id: '/urun/$slug',
  path: '/urun/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cok-satanlar': typeof CokSatanlarRoute
  '/favoriler': typeof FavorilerRoute
  '/hesabim': typeof HesabimRoute
  '/sepet': typeof SepetRoute
  '/stil-danismani': typeof StilDanismaniRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/siparisler': typeof AdminSiparislerRoute
  '/admin/urunler': typeof AdminUrunlerRoute
  '/api/stil-danismani': typeof ApiStilDanismaniRoute
  '/bilgi/$slug': typeof BilgiSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cok-satanlar': typeof CokSatanlarRoute
  '/favoriler': typeof FavorilerRoute
  '/hesabim': typeof HesabimRoute
  '/sepet': typeof SepetRoute
  '/stil-danismani': typeof StilDanismaniRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/siparisler': typeof AdminSiparislerRoute
  '/admin/urunler': typeof AdminUrunlerRoute
  '/api/stil-danismani': typeof ApiStilDanismaniRoute
  '/bilgi/$slug': typeof BilgiSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cok-satanlar': typeof CokSatanlarRoute
  '/favoriler': typeof FavorilerRoute
  '/hesabim': typeof HesabimRoute
  '/sepet': typeof SepetRoute
  '/stil-danismani': typeof StilDanismaniRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/siparisler': typeof AdminSiparislerRoute
  '/admin/urunler': typeof AdminUrunlerRoute
  '/api/stil-danismani': typeof ApiStilDanismaniRoute
  '/bilgi/$slug': typeof BilgiSlugRoute
  '/kategori/$slug': typeof KategoriSlugRoute
  '/urun/$slug': typeof UrunSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cok-satanlar'
    | '/favoriler'
    | '/hesabim'
    | '/sepet'
    | '/stil-danismani'
    | '/admin/ayarlar'
    | '/admin/kategoriler'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/api/stil-danismani'
    | '/bilgi/$slug'
    | '/kategori/$slug'
    | '/urun/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cok-satanlar'
    | '/favoriler'
    | '/hesabim'
    | '/sepet'
    | '/stil-danismani'
    | '/admin/ayarlar'
    | '/admin/kategoriler'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/api/stil-danismani'
    | '/bilgi/$slug'
    | '/kategori/$slug'
    | '/urun/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cok-satanlar'
    | '/favoriler'
    | '/hesabim'
    | '/sepet'
    | '/stil-danismani'
    | '/admin/ayarlar'
    | '/admin/kategoriler'
    | '/admin/siparisler'
    | '/admin/urunler'
    | '/api/stil-danismani'
    | '/bilgi/$slug'
    | '/kategori/$slug'
    | '/urun/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CokSatanlarRoute: typeof CokSatanlarRoute
  FavorilerRoute: typeof FavorilerRoute
  HesabimRoute: typeof HesabimRoute
  SepetRoute: typeof SepetRoute
  StilDanismaniRoute: typeof StilDanismaniRoute
  ApiStilDanismaniRoute: typeof ApiStilDanismaniRoute
  BilgiSlugRoute: typeof BilgiSlugRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
  UrunSlugRoute: typeof UrunSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cok-satanlar': {
      id: '/cok-satanlar'
      path: '/cok-satanlar'
      fullPath: '/cok-satanlar'
      preLoaderRoute: typeof CokSatanlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoriler': {
      id: '/favoriler'
      path: '/favoriler'
      fullPath: '/favoriler'
      preLoaderRoute: typeof FavorilerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hesabim': {
      id: '/hesabim'
      path: '/hesabim'
      fullPath: '/hesabim'
      preLoaderRoute: typeof HesabimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sepet': {
      id: '/sepet'
      path: '/sepet'
      fullPath: '/sepet'
      preLoaderRoute: typeof SepetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stil-danismani': {
      id: '/stil-danismani'
      path: '/stil-danismani'
      fullPath: '/stil-danismani'
      preLoaderRoute: typeof StilDanismaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ayarlar': {
      id: '/admin/ayarlar'
      path: '/ayarlar'
      fullPath: '/admin/ayarlar'
      preLoaderRoute: typeof AdminAyarlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kategoriler': {
      id: '/admin/kategoriler'
      path: '/kategoriler'
      fullPath: '/admin/kategoriler'
      preLoaderRoute: typeof AdminKategorilerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/siparisler': {
      id: '/admin/siparisler'
      path: '/siparisler'
      fullPath: '/admin/siparisler'
      preLoaderRoute: typeof AdminSiparislerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/urunler': {
      id: '/admin/urunler'
      path: '/urunler'
      fullPath: '/admin/urunler'
      preLoaderRoute: typeof AdminUrunlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/stil-danismani': {
      id: '/api/stil-danismani'
      path: '/api/stil-danismani'
      fullPath: '/api/stil-danismani'
      preLoaderRoute: typeof ApiStilDanismaniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilgi/$slug': {
      id: '/bilgi/$slug'
      path: '/bilgi/$slug'
      fullPath: '/bilgi/$slug'
      preLoaderRoute: typeof BilgiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/urun/$slug': {
      id: '/urun/$slug'
      path: '/urun/$slug'
      fullPath: '/urun/$slug'
      preLoaderRoute: typeof UrunSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAyarlarRoute: typeof AdminAyarlarRoute
  AdminKategorilerRoute: typeof AdminKategorilerRoute
  AdminSiparislerRoute: typeof AdminSiparislerRoute
  AdminUrunlerRoute: typeof AdminUrunlerRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAyarlarRoute: AdminAyarlarRoute,
  AdminKategorilerRoute: AdminKategorilerRoute,
  AdminSiparislerRoute: AdminSiparislerRoute,
  AdminUrunlerRoute: AdminUrunlerRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CokSatanlarRoute: CokSatanlarRoute,
  FavorilerRoute: FavorilerRoute,
  HesabimRoute: HesabimRoute,
  SepetRoute: SepetRoute,
  StilDanismaniRoute: StilDanismaniRoute,
  ApiStilDanismaniRoute: ApiStilDanismaniRoute,
  BilgiSlugRoute: BilgiSlugRoute,
  KategoriSlugRoute: KategoriSlugRoute,
  UrunSlugRoute: UrunSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
